from services.progression_service import invalidate_progression_settings_cache,get_effective_progression_settings,classify_set_progression,calculate_set_specific_progression
from services.workout_service import WorkoutStateService
def test_contract(): assert callable(calculate_set_specific_progression) and WorkoutStateService.first_incomplete_set([{"done":False}])==0
