name: ironcycle_billing
description: IronCycle Google Play Billing Flet service
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flet:
    path: ../../../../../../../packages/flet
  in_app_purchase: 3.2.3
  in_app_purchase_android: 0.4.0+6
